### ISSUE TITLE
volk_profile

### ISSUE THREAD

**Issue by petrushy** [conda-forge/gnuradio-satellites-feedstock#1]
It seems some issues with frame decoding are solved by running volk_profile.

https://gr-satellites.readthedocs.io/en/latest/installation.html

Should we run this post installation of the package automatically? It takes quite some time so not sure, but reduces some issues.

Regards

**Comment by ryanvolz** [comment]
I think the only way to do something like this is with a post-link script, and generally those are [discouraged unless there is no other way](https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html). As nice as it would be to have a fresh conda install take care of this and other things (notably related to SDR hardware) out of the box, I think we're best off leaving such things to the user. Especially in this case where `volk_profile` would modify a file outside of the conda prefix, and I can see that being unexpected and causing problems. I think the best solution involves documenting this in a very visible place, as is done the the `gr-satellites` docs.

**Comment by petrushy** [comment]
Yes, I agree. It could indeed be another source of issues that one environment start to affect files of used in another (outside the prefix).. 

Thanks for clarifying.
